#!/bin/sh
. "$(dirname -- "$0")/_/husky.sh"

# Load nvm if present (to ensure pnpm is available in GUI clients)
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

pnpm lint || (pnpm lint:fix && git add -A && pnpm lint)
